Add minimal pre-commit config
Uninett/argus_ticket_rt pull request #15
Opened 2023-02-06 11:32 UTC by hmpf

2023-02-10 09:24 UTC, johannaengland requested changes
Maybe also add black while you're at it?

And the pre-commit should be added to the README.

2023-02-10 09:26 UTC, hmpf commented
> Maybe also add black while you're at it?

I wouldn't call a pre-commit with black "minimal" :)

> And the pre-commit should be added to the README.

Willdo.

2023-02-10 10:37 UTC, johannaengland requested changes
I was more thinking to do it the way it is mentioned in the Argus README (https://github.com/Uninett/Argus#code-style) for consistency

2023-02-10 11:59 UTC, hmpf commented
I do not have the brains for mind-reading today, and I'm once again out of caffeine. Please update (or close) the PR as you see fit. This is just polish, a nice to have. The important one, #13, has already been merged.

2023-02-13 11:47 UTC, hmpf commented on .pre-commit-config.yaml
> +        exclude: migrations/
Ticket-plugins will never have migrations. Then they would be apps and would have to be put into INSTALLED_APPS as well.

2023-02-17 08:21 UTC, lunkwill42 approved these changes

2023-02-20 09:00 UTC, merged